services:
  db:
    container_name: teapts_backend_db
    image: postgres:18
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - tea_pts_db:/var/lib/postgresql
    networks:
      - app

  server:
    container_name: teapts_backend
    build:
      context: https://github.com/Projetario-UTFPR/teapts-backend.git#dev
    image: teapts-backend
    env_file:
      - .env
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - app
    healthcheck:
      test: ["CMD-SHELL", "psql -U ${DB_USER} -d ${DB_NAME} -c 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  tea_pts_db:

networks:
  app: